set -gx HOMEBREW_CURLRC 1
set -gx HOMEBREW_NO_ANALYTICS 1
set -gx HOMEBREW_NO_AUTO_UPDATE 1
set -gx HOMEBREW_NO_INSTALL_CLEANUP 1
# set -gx HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK 1
set -gx HOMEBREW_GITHUB_API_TOKEN (kv get HOMEBREW_GITHUB_API_TOKEN)
set -gx ANDROID_SDK "$HOME/Library/Android/sdk"
